name: Sync Open PR Branches

on:
  push:
    branches:
      - develop

jobs:
  sync-open-pr-branches:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: List Open PRs
        uses: chrisaddy/list-open-prs@0.1.0
        id: list-prs
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Sync PR Branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "List of open PR branches:"
          echo "${{ steps.list-prs.outputs.pr-branches }}"
          
          # Read and iterate through each branch
          echo "${{ steps.list-prs.outputs.pr-branches }}" | jq -r '.[]' | while read branch; do
            echo "Syncing branch: $branch"
            gh workflow run monoku/sync-branches-pr@0.0.1 \
              -from develop \
              -to $branch
          done
