name: autoupdate
on:
  pull_request_target:
    types:
      - opened
      - synchronize

jobs:
  autoupdate:
    name: autoupdate
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Update pull request branch
        uses: castastrophe/actions-pr-auto-update@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Use the default GITHUB_TOKEN
        with:
          target_branch: ${{ github.event.pull_request.base.ref }}  # Use the PR's target branch
          skip_conflict_prs: true  # Skip PRs with merge conflicts
