name: Sync PR Branches

on:
  pull_request:
    types:
      - closed

jobs:
  sync-pr-branches:
    if: >
      ${{ 
        github.event.pull_request.merged == true && 
        contains(join(',', github.event.pull_request.labels.*.name), 'PR: require post-merge sync') 
      }}
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Fetch all open PR branches
        id: fetch-pr-branches
        run: |
          PR_BRANCHES=$(gh pr list --state open --json headRefName --jq '.[].headRefName')
          echo "branches=$PR_BRANCHES" >> $GITHUB_ENV

      - name: Sync each branch with develop
        uses: connor-baer/action-sync-branch@main
        with:
          branch: ${{ env.branches }}
          token: ${{ secrets.GITHUB_TOKEN }}
          base: develop
